<a href="https://colab.research.google.com/github/joshuamichaelpeter62/Pytorch_beginner/blob/main/00_pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# pytorch fundamental

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(torch.__version__)

2.11.0+cu128


In [3]:
#!pip list

In [4]:
!nvidia-smi

Wed Sep  9 06:10:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

introduction to tensor
creating tensor

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
#matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[[
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
]]]])
TENSOR

tensor([[[[[ 2,  4,  6],
           [ 3,  6,  9],
           [ 4,  8, 12]]]]])

In [12]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [13]:
TENSOR[0]

tensor([[[[ 2,  4,  6],
          [ 3,  6,  9],
          [ 4,  8, 12]]]])

#Random tensor

In [14]:
# create random tensor
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.3062, 0.4552, 0.8387, 0.2974],
        [0.1278, 0.0793, 0.5994, 0.0340],
        [0.3538, 0.1029, 0.2242, 0.1380],
        [0.0103, 0.6638, 0.1206, 0.3667]])

In [15]:
# create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, weight and color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
# create tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zeros* random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# create tensor of all ones
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

## create range of tensor

In [20]:
# use torch.range()
torch.arange(start=0, end=1000, step= 84)

tensor([  0,  84, 168, 252, 336, 420, 504, 588, 672, 756, 840, 924])

In [21]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# create tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes

In [23]:
# float 32
float_32_tensor = torch.tensor([4.32, 6.3, 9.3],
                               dtype= None, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False) # whether or not to track gradient
float_32_tensor

tensor([4.3200, 6.3000, 9.3000])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4.3203, 6.3008, 9.2969], dtype=torch.float16)

In [26]:
float_64_tensor = torch.tensor([4.32, 6.3, 9.3],
                               dtype= torch.float64, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False) # whether or not to track gradient
float_64_tensor

tensor([4.3200, 6.3000, 9.3000], dtype=torch.float64)

In [27]:
float_64_tensor.dtype

torch.float64

In [28]:
float_16_tensor * float_64_tensor

tensor([18.6638, 39.6949, 86.4609], dtype=torch.float64)

In [29]:
float_16_tensor.dtype

torch.float16

In [30]:
torch_32_tensor = torch.tensor([4, 6, 9],
                               dtype= torch.int32, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False)
torch_32_tensor

tensor([4, 6, 9], dtype=torch.int32)

In [31]:
torch_32_tensor.dtype

torch.int32

### Getting information from data
1. tensor not right datatype - to get datatype from tensor can use tensor.dtype
2. tenosr not right shape- to get shape from a tensor can use tensor.shape
3. tensor not on right device- to get device from a tensor, can use tensor.device

# manipluting tensor
tensor operation:
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [32]:
 tensor_operation = torch.tensor([2, 5, 9])
 tensor_operation

tensor([2, 5, 9])

In [33]:
# pytorch in build function
multiplication =torch.mul(tensor_operation, 10)
multiplication

tensor([20, 50, 90])

In [34]:
torch.add(tensor_operation, 10)

tensor([12, 15, 19])

# matrix multiplication
1. Element wise muliplication
2. Matrix multiplication (dot production)

In [35]:
# Element wise muliplication
print(tensor_operation, "*", tensor_operation)
print(f"Equals: {tensor_operation * tensor_operation}")

tensor([2, 5, 9]) * tensor([2, 5, 9])
Equals: tensor([ 4, 25, 81])


In [36]:
from ast import operator
# matrix multiplication
torch.matmul(tensor_operation, tensor_operation)

tensor(110)

In [37]:
%%time
value = 0
for i in range(len(tensor_operation)):
    value += tensor_operation[i] * tensor_operation[i]
print(value)


tensor(110)
CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 5.25 ms


In [38]:
%%time
torch.matmul(tensor_operation, tensor_operation)

CPU times: user 624 µs, sys: 82 µs, total: 706 µs
Wall time: 4.88 ms


tensor(110)

## Rules that perform matrix multiplication
1. The inner dimensions match
* '(3, 2) @ (3, 2)' won't work
* '(2, 3) @ (3, 2)' will work
* '(3, 2) @ (2, 3)' will work
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> "(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

In [39]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[1.8894, 0.8792, 3.2195],
        [2.3581, 1.1384, 3.7601],
        [1.4182, 1.4178, 3.3283]])

# common mistake in deep learning is shape error

In [40]:
# operation in tensor
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [42]:
x = torch.arange(1, 10)
x.shape

torch.Size([9])

In [45]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
torch.min(x)

tensor(1)

In [46]:
x[0]

tensor(1)

In [47]:
torch.mean(x.type(torch.float32))

tensor(5.)

In [48]:
torch.max(x)

tensor(9)

In [49]:
# add an extra dimesion
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [52]:
# change the element
z[:, 0] = 5
z

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])