<a href="https://colab.research.google.com/github/joshuamichaelpeter62/Pytorch_beginner/blob/main/00_pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
# pytorch fundamental

In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(torch.__version__)

2.11.0+cpu


In [81]:
#!pip list

In [82]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


introduction to tensor
creating tensor

In [83]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [84]:
scalar.ndim

0

In [85]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [86]:
#matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [87]:
MATRIX.ndim

2

In [88]:
MATRIX.shape

torch.Size([2, 2])

In [89]:
TENSOR = torch.tensor([[[[
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
]]]])
TENSOR

tensor([[[[[ 2,  4,  6],
           [ 3,  6,  9],
           [ 4,  8, 12]]]]])

In [90]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [91]:
TENSOR[0]

tensor([[[[ 2,  4,  6],
          [ 3,  6,  9],
          [ 4,  8, 12]]]])

#Random tensor

In [92]:
# create random tensor
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.1252, 0.6332, 0.7933, 0.2622],
        [0.3611, 0.3163, 0.6394, 0.7383],
        [0.7455, 0.7976, 0.8476, 0.5400],
        [0.6130, 0.6337, 0.4358, 0.2802]])

In [93]:
# create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, weight and color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [94]:
# create tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [95]:
zeros* random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [96]:
# create tensor of all ones
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
ones.dtype

torch.float32

## create range of tensor

In [98]:
# use torch.range()
torch.arange(start=0, end=1000, step= 84)

tensor([  0,  84, 168, 252, 336, 420, 504, 588, 672, 756, 840, 924])

In [99]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
# create tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes

In [101]:
# float 32
float_32_tensor = torch.tensor([4.32, 6.3, 9.3],
                               dtype= None, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False) # whether or not to track gradient
float_32_tensor

tensor([4.3200, 6.3000, 9.3000])

In [102]:
float_32_tensor.dtype

torch.float32

In [103]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4.3203, 6.3008, 9.2969], dtype=torch.float16)

In [104]:
float_64_tensor = torch.tensor([4.32, 6.3, 9.3],
                               dtype= torch.float64, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False) # whether or not to track gradient
float_64_tensor

tensor([4.3200, 6.3000, 9.3000], dtype=torch.float64)

In [105]:
float_64_tensor.dtype

torch.float64

In [106]:
float_16_tensor * float_64_tensor

tensor([18.6638, 39.6949, 86.4609], dtype=torch.float64)

In [107]:
float_16_tensor.dtype

torch.float16

In [108]:
torch_32_tensor = torch.tensor([4, 6, 9],
                               dtype= torch.int32, # what the datatype
                               device=None, # what device is your tensor
                               requires_grad=False)
torch_32_tensor

tensor([4, 6, 9], dtype=torch.int32)

In [109]:
torch_32_tensor.dtype

torch.int32

### Getting information from data
1. tensor not right datatype - to get datatype from tensor can use tensor.dtype
2. tenosr not right shape- to get shape from a tensor can use tensor.shape
3. tensor not on right device- to get device from a tensor, can use tensor.device

# manipluting tensor
tensor operation:
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [110]:
 tensor_operation = torch.tensor([2, 5, 9])
 tensor_operation

tensor([2, 5, 9])

In [111]:
# pytorch in build function
multiplication =torch.mul(tensor_operation, 10)
multiplication

tensor([20, 50, 90])

In [112]:
torch.add(tensor_operation, 10)

tensor([12, 15, 19])

# matrix multiplication
1. Element wise muliplication
2. Matrix multiplication (dot production)

In [113]:
# Element wise muliplication
print(tensor_operation, "*", tensor_operation)
print(f"Equals: {tensor_operation * tensor_operation}")

tensor([2, 5, 9]) * tensor([2, 5, 9])
Equals: tensor([ 4, 25, 81])


In [114]:
from ast import operator
# matrix multiplication
torch.matmul(tensor_operation, tensor_operation)

tensor(110)

In [115]:
%%time
value = 0
for i in range(len(tensor_operation)):
    value += tensor_operation[i] * tensor_operation[i]
print(value)


tensor(110)
CPU times: user 1.13 ms, sys: 12 µs, total: 1.14 ms
Wall time: 995 µs


In [116]:
%%time
torch.matmul(tensor_operation, tensor_operation)

CPU times: user 0 ns, sys: 552 µs, total: 552 µs
Wall time: 443 µs


tensor(110)

## Rules that perform matrix multiplication
1. The inner dimensions match
* '(3, 2) @ (3, 2)' won't work
* '(2, 3) @ (3, 2)' will work
* '(3, 2) @ (2, 3)' will work
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> "(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

In [117]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.0857, 3.1048, 2.7437],
        [1.5281, 2.0328, 1.6390],
        [2.4627, 2.5397, 2.5286]])

# common mistake in deep learning is shape error

# reshaping, stacking, squeezing and unsqueezing tensor
* Reshaping: reshaping an input tensor to a defend shape
* View: Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking: combine multiple tensor on top of each other (vstack) or side (hstack)
* Squeeze: Remove dimension from tensor
* unsqueeze: add dimension to a target tensor
* Permute: Return a view of the input with dimensions permuted

In [118]:
# operation in tensor
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [119]:
h_stack_A = torch.hstack((tensor_A,))
h_stack_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [120]:
v_stack_A = torch.vstack((tensor_A,))
v_stack_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [121]:
x = torch.arange(1, 10)
x.shape

torch.Size([9])

In [122]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
torch.min(x)

tensor(1)

In [124]:
x[0]

tensor(1)

In [125]:
torch.mean(x.type(torch.float32))

tensor(5.)

In [126]:
torch.max(x)

tensor(9)

In [127]:
# add an extra dimesion
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [128]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [129]:
# change the element
z[:, 0] = 5
z

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [130]:
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [131]:
# v stack
x_vstack = torch.vstack([x,x,x])
x_vstack

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [132]:
# h stack
h_stack = torch.hstack([x,x,x])
h_stack

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9])

In [133]:
# squeeze and unsqueeze
squ = torch.zeros(2, 1, 2, 1, 2)
squ.size()

torch.Size([2, 1, 2, 1, 2])

In [134]:
y_squ = torch.squeeze(squ)
y_squ.size()

torch.Size([2, 2, 2])

In [135]:
y_squ = torch.squeeze(squ, 0)
y_squ.size()

torch.Size([2, 1, 2, 1, 2])

In [136]:
y_squ = torch.squeeze(squ, 1)
y_squ.size()

torch.Size([2, 2, 1, 2])

In [137]:
y_squ = torch.squeeze(squ, (1,2,3))
y_squ.size()

torch.Size([2, 2, 2])

In [138]:
# torch.unsqueeze() - add single dimesion to a target tensor at specific dim
print(f"previous target: {y_squ.shape}")
y_unsqu = y_squ.unsqueeze(dim=0)
print(f"new target: {y_unsqu.shape}")

previous target: torch.Size([2, 2, 2])
new target: torch.Size([1, 2, 2, 2])


In [139]:
# torch.permute - rearrange the dimesion of a target tensor in specific order
x_original = torch.rand(size=(224,224,3))
x_original

# permut the orginal tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # color channel height and width

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [140]:
x_original[0, 0, 0]= 20263
x_original

tensor([[[2.0263e+04, 1.1878e-02, 5.2294e-01],
         [3.1237e-01, 1.9556e-01, 4.7876e-01],
         [4.2054e-01, 3.7650e-01, 4.8959e-01],
         ...,
         [9.4681e-02, 6.5719e-01, 1.1276e-01],
         [2.5207e-01, 7.6309e-02, 8.9991e-01],
         [9.3660e-03, 6.6578e-01, 8.5713e-01]],

        [[3.3916e-01, 4.6849e-02, 4.1469e-01],
         [1.5247e-01, 8.5601e-01, 8.8980e-01],
         [2.4916e-01, 7.5927e-01, 1.1390e-01],
         ...,
         [7.6006e-01, 8.5264e-01, 3.0128e-01],
         [8.8201e-01, 6.9238e-01, 8.1834e-01],
         [1.8027e-01, 1.8561e-01, 5.0463e-01]],

        [[9.6308e-01, 2.0120e-01, 5.7474e-01],
         [4.2136e-01, 1.8667e-01, 4.1851e-01],
         [1.1185e-01, 7.4503e-01, 5.9763e-01],
         ...,
         [8.2430e-01, 8.9192e-01, 4.8384e-01],
         [1.2452e-01, 6.8217e-01, 9.5590e-01],
         [3.9398e-01, 6.3189e-01, 7.8748e-02]],

        ...,

        [[2.1946e-01, 5.3023e-01, 8.0275e-01],
         [1.7525e-01, 8.4212e-01, 1.9751e-01]

## indexing (selecting data from tensors
indexing with Pytorch is similar to indexing with numpy

In [141]:
# create tensor
q = torch.arange(1, 10).reshape(1,3,3)
q,q.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [142]:
# lets index on our new tensor
q[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [143]:
q[0][1]

tensor([4, 5, 6])

In [144]:
# let index on the most inner bracket
q[0][0][2]

tensor(3)

In [145]:
# get all value of the 0 dimensions but only index 1 of 2nd dimension
q[:,:, 1]

tensor([[2, 5, 8]])

In [146]:
# get all value of 0 dimension but only the 1 index value of 1st and 2nd dimension
q[:, 1,1]

tensor([5])

In [147]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
q[0, 0, 1]

tensor(2)

In [148]:
q

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [149]:
# index on x to return 9
q[:,2,2]

tensor([9])

In [150]:
# index on x to return 3, 6, 9
q[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensor and numpy
Numpy is a popular scientific python numerical computing library.
And because of this, pytorch has functionality to interact with it
* Data is Numpy want in pytorch tensor ->  torch. form_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.tensor.numpy()

In [151]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [152]:
tensor.dtype

torch.float32

In [153]:
# change the value of array, what will this do to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [154]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [158]:
# change the tensor what happened to numpy tensor
tensor = tensor + 2
tensor, numpy_tensor

(tensor([5., 5., 5., 5., 5., 5., 5.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## pytorch reproducbility (trying to take random out of random)
'start with random number -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again

In [159]:
torch.rand(3,3)

tensor([[0.6063, 0.5945, 0.9674],
        [0.0262, 0.4663, 0.4068],
        [0.5802, 0.6577, 0.2050]])

In [160]:
# create random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(f"random tensor A: {random_tensor_A}")
print(f"random tensor B: {random_tensor_B}")
print(random_tensor_A == random_tensor_B)

random tensor A: tensor([[0.4594, 0.0655, 0.7402, 0.8966],
        [0.8240, 0.6794, 0.9920, 0.2162],
        [0.8774, 0.5568, 0.1279, 0.1101]])
random tensor B: tensor([[0.5855, 0.3242, 0.0291, 0.9670],
        [0.6013, 0.9900, 0.0544, 0.6925],
        [0.8351, 0.5970, 0.7675, 0.7551]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
